/*
 * Pulse-Protocol ER study quiz — question bank.
 *
 * Question shape:
 *   { id: 'card-01', cat: 'cardiac', q: '...', options: [4 strings], correct: <index>, explain: '...' }
 *
 * `id` must be unique and stable — missed-question review is stored in localStorage by id.
 * `cat` must be one of the keys in CATEGORIES.
 * Options are shuffled at runtime, so never write options like "Both A and B" or "All of the above".
 * Education only; content reflects common US ED references (AHA ACLS/PALS, ESI v4, ATLS, etc.).
 */
(function (root) {
  'use strict';

  var CATEGORIES = {
    cardiac: { label: 'Cardiac', color: '#E5533D' },
    resp: { label: 'Respiratory', color: '#2FB8C6' },
    trauma: { label: 'Trauma', color: '#F2A93B' },
    neuro: { label: 'Neuro', color: '#B98CE0' },
    tox: { label: 'Toxicology', color: '#7FD1AE' },
    peds: { label: 'Pediatrics', color: '#F28FB1' },
    triage: { label: 'Triage', color: '#6FA8FF' },
    meds: { label: 'Meds & calcs', color: '#35D07F' }
  };

  var QUESTIONS = [
    // ───────────────────────── CARDIAC ─────────────────────────
    { id: 'card-01', cat: 'cardiac',
      q: '12-lead shows ST elevation in II, III, and aVF. Which artery is most likely occluded, and what\'s your next priority?',
      options: ['LAD — prep for anterior wall complications', 'RCA — inferior MI, get a right-sided ECG for RV involvement', 'Circumflex — lateral MI, monitor for AV block only', 'LAD diagonal — no special precautions needed'], correct: 1,
      explain: 'II, III, aVF = inferior leads = RCA territory in most patients. A right-sided ECG (V4R) checks for RV infarct — critical because nitrates can drop BP dangerously in preload-dependent RV infarction.' },
    { id: 'card-02', cat: 'cardiac',
      q: 'Potassium comes back at 7.2 mEq/L. Which ECG change would you expect to see first?',
      options: ['Peaked T waves', 'Delta wave', 'Prolonged QT with U waves', 'Osborn (J) waves'], correct: 0,
      explain: 'Peaked, narrow T waves are the earliest sign of hyperkalemia. As K+ rises further you see P-wave flattening, QRS widening, and eventually a sine-wave pattern. U waves suggest HYPOkalemia; Osborn waves suggest hypothermia; delta waves suggest WPW.' },
    { id: 'card-03', cat: 'cardiac',
      q: 'Your patient becomes unresponsive and pulseless; the monitor shows ventricular fibrillation. CPR is started and the defibrillator is attached. What is the priority?',
      options: ['Epinephrine 1 mg IV before any shock', 'Defibrillate as soon as possible', 'Amiodarone 300 mg IV, then shock', 'Synchronized cardioversion at 100 J'], correct: 1,
      explain: 'VF is a shockable rhythm; early defibrillation is the single most important intervention. Epinephrine is given after the 2nd shock and amiodarone/lidocaine after the 3rd in the adult algorithm. VF has no organized QRS to synchronize to, so cardioversion is inappropriate.' },
    { id: 'card-04', cat: 'cardiac',
      q: 'During a code the rhythm is asystole, confirmed in two leads. Which medication is indicated?',
      options: ['Atropine 1 mg IV', 'Amiodarone 300 mg IV', 'Epinephrine 1 mg IV/IO every 3–5 minutes', 'Adenosine 6 mg rapid IV push'], correct: 2,
      explain: 'Asystole/PEA are non-shockable: high-quality CPR plus epinephrine 1 mg as soon as feasible, repeated every 3–5 minutes, while searching for reversible causes (Hs & Ts). Atropine was removed from the PEA/asystole algorithm in 2010.' },
    { id: 'card-05', cat: 'cardiac',
      q: 'A stable patient has a regular narrow-complex tachycardia at 190 bpm. Vagal maneuvers failed. What is next?',
      options: ['Adenosine 6 mg rapid IV push followed by a saline flush', 'Immediate unsynchronized defibrillation', 'Atropine 1 mg IV', 'Amiodarone 300 mg IV push'], correct: 0,
      explain: 'For stable regular narrow-complex SVT, adenosine 6 mg rapid IV push (then 12 mg if needed) through a proximal line with an immediate flush is next after vagal maneuvers. Record a rhythm strip while pushing.' },
    { id: 'card-06', cat: 'cardiac',
      q: 'A patient with a narrow-complex tachycardia at 180 bpm is now hypotensive, diaphoretic, and confused. What is the treatment?',
      options: ['Adenosine 12 mg IV', 'Synchronized cardioversion', 'Diltiazem 0.25 mg/kg IV', 'Observe and repeat vitals in 15 minutes'], correct: 1,
      explain: 'Signs of instability (hypotension, altered mental status, shock, ischemic chest pain, acute heart failure) caused by the tachycardia call for immediate synchronized cardioversion. Sedate if time allows, but do not delay.' },
    { id: 'card-07', cat: 'cardiac',
      q: 'Symptomatic bradycardia at 38 bpm with hypotension persists after atropine. What are the next options?',
      options: ['Adenosine or diltiazem', 'Transcutaneous pacing, or a dopamine or epinephrine infusion', 'Unsynchronized defibrillation', 'Amiodarone infusion'], correct: 1,
      explain: 'If atropine is ineffective, the ACLS bradycardia algorithm moves to transcutaneous pacing and/or a chronotropic infusion (dopamine 5–20 mcg/kg/min or epinephrine 2–10 mcg/min), and expert consultation for transvenous pacing.' },
    { id: 'card-08', cat: 'cardiac',
      q: 'Which describes high-quality adult CPR compressions?',
      options: ['Rate 80–100/min, depth 1–1.5 inches', 'Rate 100–120/min, depth at least 2 inches (5 cm) but not more than 2.4 inches (6 cm), full recoil', 'Rate 120–140/min, depth 3 inches', 'Rate 100/min, pause every 10 compressions to check a pulse'], correct: 1,
      explain: 'Push hard and fast: 100–120/min, 2–2.4 inches deep, allow full chest recoil, minimize interruptions (<10 s), and avoid excessive ventilation. Rotate compressors every 2 minutes to prevent fatigue.' },
    { id: 'card-09', cat: 'cardiac',
      q: 'Which lab test is preferred to diagnose acute myocardial infarction in the ED?',
      options: ['CK-MB', 'Myoglobin', 'High-sensitivity cardiac troponin, with a repeat level', 'BNP'], correct: 2,
      explain: 'Cardiac troponin (ideally high-sensitivity) is the preferred biomarker; a rise and/or fall on serial measurements with at least one value above the 99th percentile supports MI. CK-MB and myoglobin are no longer recommended for diagnosis.' },
    { id: 'card-10', cat: 'cardiac',
      q: 'A patient with inferior STEMI has BP 86/58 and clear lungs; a right-sided ECG shows ST elevation in V4R. Which order should you question?',
      options: ['Aspirin 324 mg chewed', 'Normal saline bolus', 'Sublingual nitroglycerin 0.4 mg', 'Activate the cath lab'], correct: 2,
      explain: 'RV infarction makes the heart preload-dependent; nitrates (and other preload reducers like morphine/diuretics) can cause profound hypotension. Hypotension itself (SBP <90) is also a nitrate contraindication. These patients often need fluids instead.' },
    { id: 'card-11', cat: 'cardiac',
      q: 'Hypotension, jugular venous distension, and muffled heart sounds after chest trauma suggest which condition?',
      options: ['Tension pneumothorax', 'Cardiac tamponade (Beck\'s triad)', 'Hemothorax', 'Aortic dissection'], correct: 1,
      explain: 'Beck\'s triad = hypotension, JVD, muffled heart sounds → cardiac tamponade. Pulsus paradoxus and electrical alternans may also be seen. Treatment is pericardial decompression (pericardiocentesis or surgical). Tension pneumothorax instead causes absent breath sounds and hyperresonance.' },
    { id: 'card-12', cat: 'cardiac',
      q: 'Suspected acute aortic dissection: tearing chest pain radiating to the back, BP 190/110, HR 105. Which medication is usually given first?',
      options: ['Nitroprusside alone', 'An IV beta-blocker such as esmolol or labetalol', 'Heparin bolus', 'Tenecteplase'], correct: 1,
      explain: 'Control heart rate first (target HR <60) with an IV beta-blocker to reduce shear stress, then add a vasodilator if needed to reach SBP ~100–120. A vasodilator alone causes reflex tachycardia. Anticoagulants and thrombolytics are contraindicated.' },
    { id: 'card-13', cat: 'cardiac',
      q: 'A comatose patient has ROSC after cardiac arrest. Which post-arrest goal is recommended?',
      options: ['Keep SBP below 90 to limit reperfusion injury', 'Hyperventilate to a PaCO2 of 25 mmHg', 'Maintain SBP ≥90 / MAP ≥65, SpO2 92–98%, and deliberate temperature control that prevents fever', 'Keep SpO2 at 100% on FiO2 1.0 for 24 hours'], correct: 2,
      explain: 'Post-cardiac-arrest care: avoid hypotension (SBP ≥90, MAP ≥65), avoid hypoxia and hyperoxia (SpO2 92–98%), normocapnia, 12-lead ECG for STEMI, and deliberate temperature control with active fever prevention in patients who do not follow commands.' },

    // ───────────────────────── RESPIRATORY ─────────────────────────
    { id: 'resp-01', cat: 'resp',
      q: 'You\'re preparing for RSI. Which combination best minimizes hemodynamic instability in a hypotensive trauma patient?',
      options: ['Propofol + succinylcholine', 'Etomidate or ketamine + rocuronium', 'Midazolam + vecuronium', 'Fentanyl alone, no paralytic'], correct: 1,
      explain: 'Etomidate and ketamine preserve blood pressure better than propofol or midazolam. Rocuronium is preferred over succinylcholine when hyperkalemia risk exists; both are acceptable paralytics otherwise. Consider reduced induction doses in shock.' },
    { id: 'resp-02', cat: 'resp',
      q: 'A patient with known COPD and chronic CO2 retention is in the ED for an exacerbation. What is the usual SpO2 target?',
      options: ['100%', '96–100%', '88–92%', '80–84%'], correct: 2,
      explain: 'In chronic hypercapnic COPD, target SpO2 88–92% using controlled oxygen (e.g., Venturi mask). Over-oxygenation can worsen hypercapnia through V/Q mismatch and the Haldane effect. Never withhold oxygen from a hypoxic patient.' },
    { id: 'resp-03', cat: 'resp',
      q: 'In a patient with an acute asthma exacerbation, which finding is the most ominous?',
      options: ['Loud expiratory wheezing', 'A "silent chest" with decreasing wheeze and drowsiness', 'Respiratory rate of 24', 'SpO2 94% on room air'], correct: 1,
      explain: 'A quiet chest means minimal air movement, and drowsiness suggests CO2 retention — signs of impending respiratory arrest. A "normal" or rising PaCO2 in a tachypneic asthmatic is also a danger sign. Prepare for escalation and possible intubation.' },
    { id: 'resp-04', cat: 'resp',
      q: 'After a long flight, a patient has sudden dyspnea, pleuritic chest pain, HR 118, and clear lungs. She is hemodynamically stable. Which imaging test is most commonly used to confirm the suspected diagnosis?',
      options: ['Chest x-ray', 'CT pulmonary angiography', 'Non-contrast CT chest', 'Echocardiogram only'], correct: 1,
      explain: 'This picture suggests pulmonary embolism. CT pulmonary angiography is the standard confirmatory test in stable patients (V/Q scan if contrast is contraindicated). A chest x-ray is often normal. Risk tools (Wells, PERC) and D-dimer guide who needs imaging.' },
    { id: 'resp-05', cat: 'resp',
      q: 'Which patient is NOT an appropriate candidate for BiPAP?',
      options: ['COPD exacerbation with pH 7.30 and PaCO2 60, alert', 'Acute cardiogenic pulmonary edema, alert and cooperative', 'Obtunded patient who is actively vomiting', 'Immunocompromised patient with mild hypoxemic respiratory failure'], correct: 2,
      explain: 'Noninvasive ventilation requires a patient who can protect their airway and cooperate. Decreased consciousness, vomiting, or copious secretions create a high aspiration risk — this patient needs a definitive airway.' },
    { id: 'resp-06', cat: 'resp',
      q: 'What is the most reliable method to confirm and continuously monitor endotracheal tube placement?',
      options: ['Auscultation of breath sounds', 'Fogging in the tube', 'Continuous waveform capnography', 'Chest rise alone'], correct: 2,
      explain: 'Continuous waveform capnography is recommended for confirming and monitoring ETT position. Clinical signs (breath sounds, fogging, chest rise) are useful but unreliable alone. A chest x-ray confirms depth, not tracheal vs esophageal placement.' },
    { id: 'resp-07', cat: 'resp',
      q: 'During CPR on an intubated patient, ETCO2 suddenly rises from 14 to 40 mmHg. What does this most likely indicate?',
      options: ['Tube dislodgement', 'Return of spontaneous circulation (ROSC)', 'Rescuer fatigue', 'Hyperventilation'], correct: 1,
      explain: 'An abrupt sustained rise in ETCO2 (typically to 35–45 mmHg) suggests ROSC. ETCO2 persistently <10 mmHg during CPR suggests poor-quality compressions. Sudden loss of the waveform suggests tube displacement.' },
    { id: 'resp-08', cat: 'resp',
      q: 'During adult CPR with an advanced airway in place, how often should you ventilate?',
      options: ['30 compressions then 2 breaths', '1 breath every 6 seconds (10/min) with continuous compressions', '1 breath every 2 seconds', '20–24 breaths per minute'], correct: 1,
      explain: 'Once an advanced airway is placed, give continuous compressions and 1 breath every 6 seconds (10/min). Hyperventilation increases intrathoracic pressure and reduces venous return and coronary perfusion.' },
    { id: 'resp-09', cat: 'resp',
      q: 'A patient with acute cardiogenic pulmonary edema has BP 190/110, SpO2 84%, and severe dyspnea. Which initial combination is most appropriate?',
      options: ['Large fluid bolus and albuterol', 'Noninvasive positive-pressure ventilation plus high-dose nitroglycerin', 'Morphine and a non-rebreather only', 'Beta-blocker IV push'], correct: 1,
      explain: 'For hypertensive acute heart failure (SCAPE), NIPPV reduces preload/afterload and work of breathing, and nitroglycerin rapidly lowers preload and afterload. Diuretics follow. Fluids would worsen edema.' },
    { id: 'resp-10', cat: 'resp',
      q: 'Your intubated patient suddenly desaturates to 78%. What is the best first step?',
      options: ['Increase PEEP to 15', 'Disconnect from the ventilator and bag with 100% O2 while assessing DOPE', 'Order a stat chest x-ray and wait', 'Give a paralytic'], correct: 1,
      explain: 'DOPE: Displacement, Obstruction, Pneumothorax, Equipment failure (and breath Stacking). Removing the ventilator from the equation by hand-bagging on 100% O2 helps distinguish equipment problems from patient problems while you check tube position, suction, and breath sounds.' },
    { id: 'resp-11', cat: 'resp',
      q: 'Without an advanced airway, which device delivers the highest FiO2?',
      options: ['Nasal cannula at 6 L/min', 'Simple face mask at 8 L/min', 'Venturi mask set to 28%', 'Non-rebreather mask at 15 L/min with a full reservoir'], correct: 3,
      explain: 'A properly fitted non-rebreather at 10–15 L/min with the reservoir bag inflated delivers roughly 60–90% FiO2. Nasal cannula provides ~24–44%, a simple mask ~35–55%, and a Venturi mask a fixed, precise lower FiO2.' },
    { id: 'resp-12', cat: 'resp',
      q: 'ABG: pH 7.28, PaCO2 58 mmHg, HCO3 25 mEq/L. How do you interpret this?',
      options: ['Metabolic acidosis, uncompensated', 'Respiratory acidosis, uncompensated (acute)', 'Respiratory alkalosis, compensated', 'Metabolic alkalosis, partially compensated'], correct: 1,
      explain: 'Low pH = acidosis. PaCO2 is high (matches acidosis → respiratory cause). HCO3 is normal, so there is no metabolic compensation yet — an acute, uncompensated respiratory acidosis (e.g., hypoventilation).' },
    { id: 'resp-13', cat: 'resp',
      q: 'Which finding in anaphylaxis indicates airway involvement that requires immediate epinephrine and airway preparation?',
      options: ['Generalized urticaria alone', 'Stridor, hoarseness, or tongue/throat swelling', 'Nausea', 'Itchy eyes'], correct: 1,
      explain: 'Stridor, hoarseness, voice change, or oropharyngeal swelling signal upper-airway edema. Give IM epinephrine immediately (0.5 mg adult, 0.01 mg/kg peds) and prepare for a difficult airway — early intubation by the most experienced provider may be needed.' },

    // ───────────────────────── TRAUMA ─────────────────────────
    { id: 'trau-01', cat: 'trauma',
      q: 'Blunt chest trauma: breath sounds absent on the left, hyperresonant to percussion, JVD present, BP dropping. What\'s your move?',
      options: ['Chest x-ray to confirm before intervening', 'Immediate needle (or finger) decompression of the left chest', 'Start a crystalloid bolus and reassess in 10 minutes', 'Apply an occlusive dressing and elevate the head of bed'], correct: 1,
      explain: 'This is tension pneumothorax — a clinical diagnosis; do not wait for imaging. Decompress immediately, then place a chest tube. ATLS (10th ed.) recommends the 4th/5th intercostal space just anterior to the mid-axillary line in adults; the 2nd ICS mid-clavicular line remains an option and is used in children.' },
    { id: 'trau-02', cat: 'trauma',
      q: 'A patient with a gunshot wound to the thigh is talking but has bright red blood spurting from the wound. What is the first action?',
      options: ['Assess airway with a jaw thrust', 'Control the hemorrhage with direct pressure or a tourniquet', 'Obtain two large-bore IVs', 'Apply a cervical collar'], correct: 1,
      explain: 'Exsanguinating external hemorrhage is controlled first (the "X" in XABCDE / "C" in C-ABC). A patient who is talking has a patent airway for now. Apply a tourniquet high and tight if direct pressure fails, and note the time.' },
    { id: 'trau-03', cat: 'trauma',
      q: 'A trauma patient is anxious and confused, with HR 130, BP 84/50, and RR 32. Estimated blood loss falls into which hemorrhage class?',
      options: ['Class I (<15%)', 'Class II (15–30%)', 'Class III (30–40%)', 'Class IV (>40%) with no pulse'], correct: 2,
      explain: 'Class III (30–40% blood volume) is when blood pressure typically falls, with marked tachycardia, tachypnea, and anxiety/confusion. Class II usually has a normal SBP with tachycardia and narrowed pulse pressure. Class III–IV usually requires blood products.' },
    { id: 'trau-04', cat: 'trauma',
      q: 'Using the adult Rule of Nines, what %TBSA is a full-thickness burn covering the entire anterior trunk and the entire right arm?',
      options: ['18%', '27%', '36%', '45%'], correct: 1,
      explain: 'Adult Rule of Nines: anterior trunk 18%, posterior trunk 18%, each arm 9%, each leg 18%, head 9%, perineum 1%. Anterior trunk (18%) + one arm (9%) = 27%. Superficial (first-degree) burns are not counted.' },
    { id: 'trau-05', cat: 'trauma',
      q: 'Using the Parkland formula (4 mL × kg × %TBSA), how much fluid does an 80 kg patient with 30% TBSA burns need in the FIRST 8 hours after the burn?',
      options: ['2,400 mL', '4,800 mL', '9,600 mL', '1,200 mL'], correct: 1,
      explain: '4 × 80 × 30 = 9,600 mL over 24 hr; half (4,800 mL) in the first 8 hours from the TIME OF INJURY, not from ED arrival. Titrate to urine output (~0.5 mL/kg/hr in adults). Many burn centers now start at 2 mL/kg/%TBSA to avoid over-resuscitation.' },
    { id: 'trau-06', cat: 'trauma',
      q: 'A head-injured patient opens eyes only to pain, makes incomprehensible sounds, and withdraws from pain. What is the GCS?',
      options: ['6', '8', '10', '12'], correct: 1,
      explain: 'Eyes to pain = 2, incomprehensible sounds = 2, withdraws from pain = 4. Total 8. "GCS 8 — intubate" is a common teaching point because of impaired airway protection, although the decision is clinical.' },
    { id: 'trau-07', cat: 'trauma',
      q: 'After a diving injury, a patient has BP 78/40, HR 52, and warm, dry skin below the level of injury. What type of shock is this?',
      options: ['Hypovolemic', 'Cardiogenic', 'Neurogenic', 'Septic'], correct: 2,
      explain: 'Neurogenic shock (typically injuries at T6 or above) causes loss of sympathetic tone: hypotension with bradycardia and warm, dry skin. Hemorrhage must still be ruled out. Treatment includes fluids, vasopressors, and atropine for bradycardia.' },
    { id: 'trau-08', cat: 'trauma',
      q: 'Where should a pelvic binder be placed for a suspected unstable pelvic fracture?',
      options: ['Over the iliac crests', 'Centered over the greater trochanters', 'Around the upper thighs', 'Around the lower abdomen at the umbilicus'], correct: 1,
      explain: 'Center the binder over the greater trochanters to close the pelvic ring and reduce pelvic volume/venous bleeding. Placing it over the iliac crests is a common error that can widen the fracture.' },
    { id: 'trau-09', cat: 'trauma',
      q: 'In a hypotensive blunt trauma patient, what is the FAST exam primarily looking for?',
      options: ['Solid organ fractures', 'Free fluid in the pericardium, peritoneum (and pleura in eFAST)', 'Rib fractures', 'Retroperitoneal bleeding'], correct: 1,
      explain: 'FAST (Focused Assessment with Sonography in Trauma) screens for free fluid (presumed blood) in the pericardial sac, RUQ, LUQ, and pelvis; eFAST adds pneumothorax and hemothorax. It is poor at detecting retroperitoneal bleeding.' },
    { id: 'trau-10', cat: 'trauma',
      q: 'For massive transfusion in hemorrhagic shock, which product strategy is recommended?',
      options: ['Crystalloid 3 L first, then packed red cells only', 'A balanced ratio of plasma, platelets, and red cells approaching 1:1:1', 'Albumin until blood is available', 'Red cells only until INR results return'], correct: 1,
      explain: 'Damage-control resuscitation uses balanced blood products (about 1:1:1) and minimizes crystalloid, which worsens dilutional coagulopathy, acidosis, and hypothermia. Add TXA within 3 hours of injury and monitor calcium.' },
    { id: 'trau-11', cat: 'trauma',
      q: 'What makes up the "lethal triad" in trauma?',
      options: ['Hypoxia, hypotension, hypoglycemia', 'Hypothermia, acidosis, coagulopathy', 'Tachycardia, tachypnea, fever', 'Hyperkalemia, hypocalcemia, hypomagnesemia'], correct: 1,
      explain: 'Hypothermia, acidosis, and coagulopathy each worsen the others. Prevent heat loss (warm room, blankets, warmed fluids/blood), restore perfusion, and correct coagulopathy with blood products. Some add hypocalcemia as a "diamond".' },
    { id: 'trau-12', cat: 'trauma',
      q: 'After hemorrhage control, which is a priority intervention for an open tibia fracture?',
      options: ['Delay antibiotics until the OR', 'Early IV antibiotics (e.g., cefazolin) and tetanus prophylaxis', 'Irrigate the wound with povidone-iodine in the ED and close it', 'Apply ice and discharge with follow-up'], correct: 1,
      explain: 'Early IV antibiotics (ideally within 1 hour) significantly reduce infection risk in open fractures; update tetanus. Cover the wound with a sterile moist dressing, splint, and check neurovascular status. Definitive washout happens in the OR.' },
    { id: 'trau-13', cat: 'trauma',
      q: 'Which is the EARLIEST and most reliable sign of acute compartment syndrome?',
      options: ['Absent distal pulses', 'Pain out of proportion to injury, especially with passive stretch', 'Pallor of the limb', 'Paralysis'], correct: 1,
      explain: 'Pain out of proportion and pain on passive stretch are early findings. Pulselessness, pallor, and paralysis are LATE — waiting for them means tissue death. Emergent fasciotomy is the definitive treatment; remove circumferential dressings/casts.' },

    // ───────────────────────── NEURO ─────────────────────────
    { id: 'neur-01', cat: 'neuro',
      q: 'Last-known-well was 2 hours ago. NIHSS 14, no contraindications on the checklist. What\'s the priority sequence?',
      options: ['MRI first to confirm ischemic vs hemorrhagic, then decide', 'Non-contrast CT (± CTA for large-vessel occlusion) stat, glucose check, and move toward thrombolytic eligibility within the window', 'Aspirin and admit for observation', 'Wait for neurology to see the patient before any imaging'], correct: 1,
      explain: 'Non-contrast CT is the fast first step to exclude hemorrhage; CTA identifies a large-vessel occlusion for thrombectomy. With onset well inside the 4.5-hour window the clock is the enemy — imaging, labs, and screening happen in parallel. Aspirin is held until hemorrhage is excluded and for 24 hr after thrombolysis.' },
    { id: 'neur-02', cat: 'neuro',
      q: 'A stroke patient is a thrombolytic candidate. BP is 196/112. What is the BP threshold before giving the drug?',
      options: ['Less than 220/120', 'Less than 185/110', 'Less than 140/90', 'No BP limit applies'], correct: 1,
      explain: 'BP must be lowered to <185/110 before thrombolysis (e.g., labetalol or nicardipine) and kept ≤180/105 for 24 hours after. For patients NOT receiving reperfusion therapy, permissive hypertension up to 220/120 is commonly allowed.' },
    { id: 'neur-03', cat: 'neuro',
      q: 'A head-injured patient develops hypertension with a widening pulse pressure, bradycardia, and irregular respirations. What does this suggest?',
      options: ['Hypovolemic shock', 'Cushing\'s triad from rising intracranial pressure', 'Neurogenic shock', 'Sepsis'], correct: 1,
      explain: 'Cushing\'s triad (hypertension/widened pulse pressure, bradycardia, irregular respirations) is a late sign of increased ICP and impending herniation. Notify the provider immediately and prepare for ICP-lowering measures and neurosurgery.' },
    { id: 'neur-04', cat: 'neuro',
      q: 'A patient has been seizing continuously for 6 minutes and has an IV in place. What is first-line treatment?',
      options: ['Levetiracetam 60 mg/kg IV', 'Lorazepam 0.1 mg/kg IV (max 4 mg), may repeat once', 'Phenobarbital PO', 'Wait until the seizure reaches 30 minutes'], correct: 1,
      explain: 'Status epilepticus is treated at ≥5 minutes. Benzodiazepines are first line: IV lorazepam 0.1 mg/kg (max 4 mg), IM midazolam 10 mg if >40 kg without IV access, or IV diazepam. Levetiracetam, fosphenytoin, or valproate are second line if seizures continue.' },
    { id: 'neur-05', cat: 'neuro',
      q: 'A stroke alert arrives with facial droop and arm weakness. Which bedside test must be done before thrombolysis?',
      options: ['Serum troponin', 'Point-of-care blood glucose', 'Urine drug screen', 'Lumbar puncture'], correct: 1,
      explain: 'Hypoglycemia can mimic stroke and is quickly reversible; glucose is the only lab required before thrombolysis in most patients (unless anticoagulation or coagulopathy is suspected). Don\'t delay treatment waiting for other labs.' },
    { id: 'neur-06', cat: 'neuro',
      q: 'A patient reports a sudden "worst headache of my life" that peaked within a minute. What is the most appropriate first diagnostic test?',
      options: ['MRI brain with contrast', 'Non-contrast CT head', 'EEG', 'Lumbar puncture before imaging'], correct: 1,
      explain: 'A thunderclap headache raises concern for subarachnoid hemorrhage. Non-contrast CT is highly sensitive when performed early (especially within 6 hours of onset). If CT is negative and suspicion remains, LP (xanthochromia) or CTA is pursued.' },
    { id: 'neur-07', cat: 'neuro',
      q: 'Right-sided arm and face weakness with expressive aphasia most likely involves which vascular territory?',
      options: ['Right middle cerebral artery', 'Left middle cerebral artery', 'Basilar artery', 'Right posterior cerebral artery'], correct: 1,
      explain: 'Motor deficits are contralateral to the lesion, and language is usually in the left hemisphere. Right-sided weakness + aphasia → left MCA. Right MCA strokes often cause left-sided weakness and neglect.' },
    { id: 'neur-08', cat: 'neuro',
      q: 'After a blow to the temple, a patient briefly lost consciousness, then was lucid, and now is rapidly deteriorating. What is most likely?',
      options: ['Subdural hematoma from bridging veins', 'Epidural hematoma from middle meningeal artery bleeding', 'Concussion only', 'Subarachnoid hemorrhage from an aneurysm'], correct: 1,
      explain: 'The classic "lucid interval" followed by rapid decline suggests an arterial epidural hematoma (often middle meningeal artery with temporal bone fracture). It is a neurosurgical emergency. Subdurals are venous and often slower, especially in the elderly.' },
    { id: 'neur-09', cat: 'neuro',
      q: 'A febrile patient has neck stiffness, headache, and confusion. CT and LP will be delayed. What is the priority?',
      options: ['Wait for CSF results before giving antibiotics', 'Draw blood cultures, then give dexamethasone and empiric IV antibiotics immediately', 'Give acetaminophen and reassess in 1 hour', 'Give antibiotics only after the CT is read'], correct: 1,
      explain: 'Suspected bacterial meningitis is time-critical. Obtain blood cultures and start empiric antibiotics (e.g., ceftriaxone + vancomycin ± ampicillin) without waiting for imaging or LP. Dexamethasone is given before or with the first antibiotic dose. Use droplet precautions.' },
    { id: 'neur-10', cat: 'neuro',
      q: 'Low back pain with new saddle anesthesia and urinary retention should make you suspect what?',
      options: ['Simple lumbar strain', 'Cauda equina syndrome — needs emergent MRI and surgical consult', 'Kidney stone', 'Sciatica needing outpatient physical therapy'], correct: 1,
      explain: 'Saddle anesthesia, urinary retention (or overflow incontinence), bowel dysfunction, and bilateral leg weakness are red flags for cauda equina compression — a surgical emergency. A post-void residual helps screen.' },
    { id: 'neur-11', cat: 'neuro',
      q: 'A head-injured patient develops a unilateral fixed, dilated pupil and worsening consciousness. Which set of temporizing measures is appropriate while arranging neurosurgery?',
      options: ['Lay flat with legs elevated and give hypotonic fluids', 'Elevate head of bed 30°, give osmotherapy (mannitol or hypertonic saline), and brief hyperventilation as a bridge', 'Give a sedative and repeat CT in 6 hours', 'Aggressive prolonged hyperventilation to PaCO2 20 mmHg'], correct: 1,
      explain: 'Signs of herniation call for ICP-lowering bridges: HOB 30° with neck midline, osmotherapy, avoiding hypotension and hypoxia, and short-term mild hyperventilation (PaCO2 ~30–35). Prolonged or aggressive hyperventilation causes cerebral ischemia.' },
    { id: 'neur-12', cat: 'neuro',
      q: 'A patient has facial droop of the lower face but can wrinkle the forehead on both sides. What does this suggest?',
      options: ['Bell\'s palsy (peripheral CN VII lesion)', 'A central (upper motor neuron) lesion such as stroke', 'Trigeminal neuralgia', 'Normal finding'], correct: 1,
      explain: 'The forehead has bilateral cortical innervation, so central lesions (stroke) spare the forehead. Bell\'s palsy (peripheral) involves the whole half of the face, including the forehead. Forehead sparing should trigger a stroke evaluation.' },
    { id: 'neur-13', cat: 'neuro',
      q: 'A patient with suspected Guillain-Barré syndrome has ascending weakness. Which monitoring is most important?',
      options: ['Hourly blood glucose', 'Serial forced vital capacity and negative inspiratory force', 'Daily weights only', 'Pupil checks every 4 hours'], correct: 1,
      explain: 'Respiratory muscle weakness can progress quickly. Falling FVC (e.g., <20 mL/kg) or weak NIF signals impending respiratory failure requiring intubation — SpO2 falls late. Also watch for autonomic instability (BP and HR swings).' },

    // ───────────────────────── TOXICOLOGY ─────────────────────────
    { id: 'tox-01', cat: 'tox',
      q: 'A patient ingested acetaminophen 5 hours ago (single acute ingestion). How do you decide on acetylcysteine?',
      options: ['Only treat if LFTs are abnormal now', 'Plot a 4-hour-or-later acetaminophen level on the Rumack-Matthew nomogram', 'Treat only if the patient is vomiting', 'Measure a level at 1 hour'], correct: 1,
      explain: 'For a known-time single acute ingestion, a level drawn ≥4 hours post-ingestion is plotted on the nomogram. LFTs are often normal early. NAC is most effective when started within 8 hours; do not wait for a level if that window will be missed.' },
    { id: 'tox-02', cat: 'tox',
      q: 'Pinpoint pupils, RR 6, and decreased consciousness suggest which toxidrome?',
      options: ['Sympathomimetic', 'Opioid', 'Anticholinergic', 'Serotonin syndrome'], correct: 1,
      explain: 'The opioid toxidrome is CNS depression, respiratory depression, and miosis. Support ventilation with a bag-valve mask and give naloxone titrated to adequate breathing. Fentanyl analogs may need repeat doses; watch for re-sedation.' },
    { id: 'tox-03', cat: 'tox',
      q: 'Which finding best distinguishes anticholinergic toxicity from sympathomimetic toxicity?',
      options: ['Tachycardia', 'Mydriasis', 'Dry, flushed skin (no sweating)', 'Hyperthermia'], correct: 2,
      explain: 'Both toxidromes cause tachycardia, hyperthermia, dilated pupils, and agitation. Anticholinergic patients are "dry as a bone" (no sweat) with urinary retention and decreased bowel sounds; sympathomimetic patients are diaphoretic.' },
    { id: 'tox-04', cat: 'tox',
      q: 'A farmworker has pinpoint pupils, drooling, vomiting, wheezing, and copious bronchial secretions. What is the endpoint for atropine dosing?',
      options: ['Heart rate over 120', 'Drying of bronchial secretions and improved oxygenation', 'Pupils return to normal size', 'Normal mental status'], correct: 1,
      explain: 'Organophosphate (cholinergic) poisoning: the "killer B\'s" — bronchorrhea, bronchospasm, bradycardia. Atropine is doubled every ~5 min until secretions dry. Tachycardia and pupil size are NOT endpoints. Pralidoxime and decontamination (with PPE) are also given.' },
    { id: 'tox-05', cat: 'tox',
      q: 'A tricyclic antidepressant overdose patient has a QRS of 130 ms and hypotension. What is the key treatment?',
      options: ['Physostigmine', 'Sodium bicarbonate IV boluses', 'Flumazenil', 'Procainamide'], correct: 1,
      explain: 'TCAs block cardiac sodium channels, widening QRS. Sodium bicarbonate (1–2 mEq/kg boluses) provides sodium and alkalinization to narrow the QRS and prevent arrhythmias. Class IA drugs (procainamide) and physostigmine are contraindicated; flumazenil can precipitate seizures.' },
    { id: 'tox-06', cat: 'tox',
      q: 'A patient rescued from a house fire has a headache and confusion; SpO2 reads 99%. What is the best next step?',
      options: ['Reassure — oxygenation is normal', '100% O2 by non-rebreather and a co-oximetry carboxyhemoglobin level', 'Room air and observe', 'Nasal cannula at 2 L/min'], correct: 1,
      explain: 'Standard pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin, so SpO2 is falsely normal in CO poisoning. Give 100% O2 immediately and check COHb by co-oximetry. Also consider cyanide toxicity (hydroxocobalamin) in smoke inhalation with high lactate.' },
    { id: 'tox-07', cat: 'tox',
      q: 'Tinnitus, vomiting, tachypnea, and an ABG showing respiratory alkalosis with an anion-gap metabolic acidosis suggest poisoning with which agent?',
      options: ['Acetaminophen', 'Salicylates (aspirin)', 'Benzodiazepines', 'Digoxin'], correct: 1,
      explain: 'Salicylates stimulate the respiratory center and cause a metabolic acidosis — a classic mixed disorder. Treat with sodium bicarbonate (urine alkalinization) and consider hemodialysis for severe cases. If intubation is unavoidable, maintain hyperventilation; losing respiratory compensation can be fatal.' },
    { id: 'tox-08', cat: 'tox',
      q: 'A beta-blocker overdose patient is bradycardic, hypotensive, and hypoglycemic. Which therapies are specifically used?',
      options: ['Flumazenil and naloxone', 'Glucagon and high-dose insulin euglycemic therapy (with fluids, calcium, pressors)', 'Physostigmine', 'Adenosine'], correct: 1,
      explain: 'Glucagon increases cAMP independent of beta receptors; high-dose insulin improves myocardial energy use. Atropine, calcium, vasopressors, and pacing are also used. Consult poison control (1-800-222-1222 in the US).' },
    { id: 'tox-09', cat: 'tox',
      q: 'Which lab finding helps distinguish calcium-channel blocker overdose from beta-blocker overdose?',
      options: ['Hypoglycemia', 'Hyperglycemia', 'Hyperkalemia', 'Elevated troponin'], correct: 1,
      explain: 'CCB toxicity blocks insulin release, causing hyperglycemia (and its degree correlates with severity). Beta-blocker overdose more often causes hypoglycemia. Treatment for CCB toxicity includes calcium, high-dose insulin, and vasopressors.' },
    { id: 'tox-10', cat: 'tox',
      q: 'A patient has an elevated anion gap, an elevated osmolar gap, and calcium oxalate crystals in the urine. Which antidote is indicated?',
      options: ['Fomepizole', 'N-acetylcysteine', 'Deferoxamine', 'Naloxone'], correct: 0,
      explain: 'This suggests ethylene glycol poisoning. Fomepizole blocks alcohol dehydrogenase, preventing formation of toxic metabolites. Hemodialysis may also be needed. Methanol causes a similar gap pattern with visual symptoms instead of oxalate crystals.' },
    { id: 'tox-11', cat: 'tox',
      q: 'A patient on an SSRI who started tramadol today is agitated, diaphoretic, and febrile. Which finding most supports serotonin syndrome over neuroleptic malignant syndrome?',
      options: ['Lead-pipe rigidity', 'Inducible clonus and hyperreflexia with rapid onset', 'Onset over several days', 'Bradyreflexia'], correct: 1,
      explain: 'Serotonin syndrome develops within hours and features clonus (especially in the lower extremities), hyperreflexia, and tremor. NMS develops over days after dopamine antagonists and features lead-pipe rigidity and slow (bradykinetic) reflexes.' },
    { id: 'tox-12', cat: 'tox',
      q: 'An elderly patient on digoxin has nausea, yellow-green visual halos, bradycardia, and a K+ of 6.1. What is the definitive treatment for life-threatening toxicity?',
      options: ['Calcium chloride IV push', 'Digoxin-specific antibody fragments (DigiFab)', 'Increase the digoxin dose', 'Amiodarone'], correct: 1,
      explain: 'Digoxin immune Fab binds digoxin and is indicated for life-threatening arrhythmias, K+ >5–5.5 in acute toxicity, or end-organ dysfunction. Hyperkalemia reflects severity. (Calcium in digoxin toxicity is controversial — defer to Fab.)' },
    { id: 'tox-13', cat: 'tox',
      q: 'A patient\'s last drink was 3 days ago. Now febrile, tachycardic, diaphoretic, confused, and hallucinating. What is this and what is first-line treatment?',
      options: ['Alcohol intoxication — observe', 'Delirium tremens — benzodiazepines titrated to effect', 'Wernicke encephalopathy — dextrose first', 'Opioid withdrawal — naloxone'], correct: 1,
      explain: 'Withdrawal seizures typically occur 6–48 hours after the last drink; delirium tremens usually 48–96 hours, with autonomic instability and altered sensorium. It can be fatal. Treat with benzodiazepines (phenobarbital is an adjunct), thiamine, fluids, and electrolytes.' },

    // ───────────────────────── PEDIATRICS ─────────────────────────
    { id: 'peds-01', cat: 'peds',
      q: 'An infant has HR 52 with poor perfusion despite adequate oxygenation and ventilation. What should you do?',
      options: ['Give atropine and wait 5 minutes', 'Start CPR (chest compressions)', 'Observe — infant heart rates vary', 'Synchronized cardioversion'], correct: 1,
      explain: 'In pediatrics, bradycardia is usually hypoxic. If HR is <60/min with signs of poor perfusion despite oxygenation and ventilation, begin chest compressions, then give epinephrine. Atropine is for increased vagal tone or primary AV block.' },
    { id: 'peds-02', cat: 'peds',
      q: 'What is the compression-to-ventilation ratio for two-rescuer CPR on a child (no advanced airway)?',
      options: ['30:2', '15:2', '5:1', '3:1'], correct: 1,
      explain: 'Two-rescuer infant/child CPR uses 15:2; single rescuer uses 30:2. Newborns (neonatal resuscitation) use 3:1. With an advanced airway, give continuous compressions and a breath every 2–3 seconds in pediatrics.' },
    { id: 'peds-03', cat: 'peds',
      q: 'How deep should chest compressions be for an infant?',
      options: ['About 0.5 inch', 'At least one-third the AP diameter of the chest (about 1.5 inches / 4 cm)', '2.4 inches (6 cm)', 'Until ribs are felt to flex'], correct: 1,
      explain: 'Infants: at least 1/3 AP diameter (~1.5 in / 4 cm). Children: at least 1/3 AP diameter (~2 in / 5 cm). Use two thumbs–encircling hands technique for infants with two rescuers.' },
    { id: 'peds-04', cat: 'peds',
      q: 'What is the minimum acceptable systolic BP for a 6-year-old (hypotension threshold)?',
      options: ['60 mmHg', '70 mmHg', '82 mmHg', '100 mmHg'], correct: 2,
      explain: 'For ages 1–10, hypotension is SBP < 70 + (2 × age in years). For a 6-year-old: 70 + 12 = 82 mmHg. Hypotension is a LATE sign of shock in children — tachycardia and poor perfusion come first.' },
    { id: 'peds-05', cat: 'peds',
      q: 'In a pediatric emergency where the weight is unknown, what is a recommended way to estimate weight for drug dosing?',
      options: ['Ask the child', 'A length-based resuscitation tape (e.g., Broselow)', 'Estimate by age alone with adult doses', 'Wait for a scale'], correct: 1,
      explain: 'Length-based tapes give a weight estimate plus pre-calculated drug doses and equipment sizes, reducing calculation errors. A measured weight in kg is preferred when available; always record weight in kilograms.' },
    { id: 'peds-06', cat: 'peds',
      q: 'A 2-year-old has a barking cough, inspiratory stridor at rest, and mild retractions. What is appropriate treatment?',
      options: ['Antibiotics and discharge', 'Dexamethasone and nebulized racemic epinephrine', 'Immediate intubation', 'Albuterol nebs only'], correct: 1,
      explain: 'Moderate–severe croup (stridor at rest): corticosteroid (dexamethasone) plus nebulized epinephrine. Observe for a few hours after epinephrine for rebound symptoms. Keep the child calm, often in a parent\'s arms.' },
    { id: 'peds-07', cat: 'peds',
      q: 'A toxic-appearing 4-year-old sits in a tripod position, drooling, with muffled voice and high fever. What should you avoid?',
      options: ['Keeping the child with a parent', 'Examining the throat with a tongue depressor or forcing the child to lie down', 'Calling anesthesia/ENT', 'Offering humidified blow-by oxygen'], correct: 1,
      explain: 'This picture suggests epiglottitis (or another deep neck infection). Agitating the child (throat exam, IV attempts, laying flat) can trigger complete obstruction. Keep the child calm and upright and secure the airway in a controlled setting (OR) with the most experienced team.' },
    { id: 'peds-08', cat: 'peds',
      q: 'A 9-month-old has intermittent episodes of inconsolable crying with legs drawn up, lethargy between episodes, and a "currant jelly" stool. What is the likely diagnosis?',
      options: ['Pyloric stenosis', 'Intussusception', 'Gastroenteritis', 'Colic'], correct: 1,
      explain: 'Intussusception peaks at 6–36 months: colicky pain, lethargy, sausage-shaped mass, and currant jelly stool (a late sign). Ultrasound is the diagnostic test; air or contrast enema is often both diagnostic and therapeutic.' },
    { id: 'peds-09', cat: 'peds',
      q: 'A 4-week-old has forceful, non-bilious projectile vomiting after every feed. Which electrolyte pattern is expected?',
      options: ['Hyperchloremic metabolic acidosis', 'Hypochloremic, hypokalemic metabolic alkalosis', 'Hyperkalemic metabolic acidosis', 'Normal electrolytes always'], correct: 1,
      explain: 'Pyloric stenosis (typically 3–6 weeks old) causes loss of gastric HCl → hypochloremic, hypokalemic metabolic alkalosis. Correct fluids and electrolytes before pyloromyotomy. Ultrasound confirms.' },
    { id: 'peds-10', cat: 'peds',
      q: 'A 10-day-old has sudden onset of BILIOUS (green) vomiting. What must be ruled out emergently?',
      options: ['Reflux', 'Malrotation with midgut volvulus', 'Milk protein allergy', 'Pyloric stenosis'], correct: 1,
      explain: 'Bilious vomiting in a neonate is a surgical emergency until proven otherwise — malrotation with volvulus can cause bowel ischemia within hours. Upper GI contrast study and urgent surgical consultation.' },
    { id: 'peds-11', cat: 'peds',
      q: 'A well-appearing 2-week-old has a rectal temperature of 38.2 °C (100.8 °F). What is the recommended approach?',
      options: ['Antipyretic and discharge with follow-up', 'Full sepsis evaluation (blood, urine, and CSF cultures), empiric IV antibiotics, and admission', 'Urinalysis only', 'Recheck the temperature in 24 hours at home'], correct: 1,
      explain: 'Febrile neonates are at high risk for serious bacterial infection (bacteremia, UTI, meningitis) even when they look well. Infants 8–21 days old with fever warrant blood, urine, and CSF studies, parenteral antibiotics, and admission (AAP 2021). Consider HSV and acyclovir.' },
    { id: 'peds-12', cat: 'peds',
      q: 'What is the usual initial fluid bolus for a child in septic shock without signs of fluid overload?',
      options: ['5 mL/kg of D5W', '10–20 mL/kg of isotonic crystalloid, reassessing after each bolus', '60 mL/kg over 5 minutes regardless of response', '30 mL/kg of albumin'], correct: 1,
      explain: 'Give 10–20 mL/kg of isotonic crystalloid (up to 40–60 mL/kg in the first hour where intensive care is available), reassessing for hepatomegaly, crackles, and worsening work of breathing after each bolus. Avoid dextrose-containing fluids for boluses.' },
    { id: 'peds-13', cat: 'peds',
      q: 'Which finding is MOST concerning for non-accidental trauma?',
      options: ['Bruises on the shins of an active 3-year-old', 'Bruising on the ear, neck, or torso of a 4-month-old non-mobile infant', 'A forehead bump in a toddler learning to walk', 'A single scraped knee'], correct: 1,
      explain: 'Any bruising in a non-mobile infant is a red flag. The TEN-4-FACESp rule flags bruising on the Torso, Ears, Neck (in any child <4 years) or any bruise in an infant ≤4 months, plus the Frenulum, Angle of jaw, Cheeks, Eyelids, Subconjunctivae, and patterned bruises. Nurses are mandated reporters.' },

    // ───────────────────────── TRIAGE ─────────────────────────
    { id: 'tria-01', cat: 'triage',
      q: 'A 34-year-old walks in with a fever of 101.2 °F, sore throat, and mild dehydration. No airway compromise, stable vitals. What ESI level?',
      options: ['ESI 1', 'ESI 2', 'ESI 3', 'ESI 5'], correct: 2,
      explain: 'ESI 3 — stable vitals and no high-risk features, but likely needs two or more resources (labs, IV fluids). Not high-risk enough for ESI 2, and too resource-intensive for ESI 4/5.' },
    { id: 'tria-02', cat: 'triage',
      q: 'Which patient is ESI 1?',
      options: ['Chest pain, diaphoretic, BP 140/90', 'Unresponsive with agonal respirations', 'Ankle deformity after a fall', 'Suicidal ideation with a plan, calm'], correct: 1,
      explain: 'ESI 1 requires an immediate life-saving intervention (airway, emergent medications, defibrillation, etc.). Unresponsiveness with agonal breathing needs immediate airway support. The chest pain and suicidal patients are high-risk ESI 2.' },
    { id: 'tria-03', cat: 'triage',
      q: 'A 58-year-old reports crushing chest pressure and is diaphoretic, but vital signs are within normal limits. What ESI level?',
      options: ['ESI 1', 'ESI 2', 'ESI 3', 'ESI 4'], correct: 1,
      explain: 'Possible ACS is a high-risk situation — ESI 2 — even with normal vitals. They should not wait; obtain a 12-lead ECG within 10 minutes of arrival.' },
    { id: 'tria-04', cat: 'triage',
      q: 'A stable patient with a twisted ankle can bear weight with a limp and will likely need only an x-ray. What ESI level?',
      options: ['ESI 2', 'ESI 3', 'ESI 4', 'ESI 5'], correct: 2,
      explain: 'One anticipated resource (x-ray) = ESI 4. Oral medications, a splint/crutches, and prescriptions are not counted as ESI resources.' },
    { id: 'tria-05', cat: 'triage',
      q: 'A well-appearing patient requests a refill of their blood pressure medication and has normal vital signs. What ESI level?',
      options: ['ESI 2', 'ESI 3', 'ESI 4', 'ESI 5'], correct: 3,
      explain: 'No resources anticipated beyond an exam and a prescription = ESI 5.' },
    { id: 'tria-06', cat: 'triage',
      q: 'An adult you would otherwise rate ESI 3 has HR 124, RR 26, and SpO2 90%. What should you do?',
      options: ['Keep ESI 3 — resources determine level', 'Consider up-triaging to ESI 2 because of danger-zone vital signs', 'Down-triage to ESI 4', 'Reassess in an hour'], correct: 1,
      explain: 'ESI decision point D: danger-zone vitals (adult HR >100, RR >20, SpO2 <92%) should prompt the nurse to consider ESI 2.' },
    { id: 'tria-07', cat: 'triage',
      q: 'Using START triage in a mass-casualty incident, an adult is not breathing. After repositioning the airway, there is still no breathing. How is this patient tagged?',
      options: ['Immediate (red)', 'Delayed (yellow)', 'Minor (green)', 'Expectant/deceased (black)'], correct: 3,
      explain: 'In adult START, no respirations after airway repositioning = expectant/deceased (black). If breathing resumes after repositioning, tag immediate (red). MCI triage aims to do the greatest good for the greatest number.' },
    { id: 'tria-08', cat: 'triage',
      q: 'START triage: an adult who cannot walk has a respiratory rate of 36. What tag?',
      options: ['Immediate (red)', 'Delayed (yellow)', 'Minor (green)', 'Expectant (black)'], correct: 0,
      explain: 'START uses RPM: Respirations >30 → immediate; Perfusion (radial pulse absent or cap refill >2 s) → immediate; Mental status (can\'t follow simple commands) → immediate. Otherwise non-ambulatory = delayed.' },
    { id: 'tria-09', cat: 'triage',
      q: 'JumpSTART (pediatric MCI triage): a child is apneic but has a palpable pulse. After airway positioning they remain apneic. What is next?',
      options: ['Tag expectant immediately', 'Give 5 rescue breaths; if breathing resumes tag immediate (red)', 'Start chest compressions for 2 minutes', 'Tag delayed and move on'], correct: 1,
      explain: 'Because pediatric arrests are often respiratory, JumpSTART adds 5 rescue breaths for an apneic child with a pulse. If spontaneous breathing resumes → immediate; if not → expectant.' },
    { id: 'tria-10', cat: 'triage',
      q: 'Which set of criteria makes up qSOFA?',
      options: ['Temp >38 °C, HR >90, WBC >12,000', 'RR ≥22, altered mentation, SBP ≤100', 'Lactate >2, MAP <65, urine output <0.5 mL/kg/hr', 'SpO2 <90%, HR >120, age >65'], correct: 1,
      explain: 'qSOFA = RR ≥22, altered mentation, SBP ≤100 (2+ suggests higher mortality risk). It is a prognostic tool, not a screening test on its own — use it alongside your facility\'s sepsis screen and lactate.' },
    { id: 'tria-11', cat: 'triage',
      q: 'In the BE-FAST stroke screening tool, what do the "B" and "E" add to FAST?',
      options: ['Blood pressure and ECG', 'Balance and Eyes (vision changes)', 'Breathing and Energy', 'Blood glucose and Electrolytes'], correct: 1,
      explain: 'BE-FAST: Balance (sudden loss/ataxia), Eyes (vision loss/diplopia), Face drooping, Arm weakness, Speech difficulty, Time to call/activate a stroke alert. B and E help catch posterior circulation strokes.' },
    { id: 'tria-12', cat: 'triage',
      q: 'A patient arrives with chest pain suggestive of ACS. Within how many minutes of arrival should a 12-lead ECG be obtained and reviewed?',
      options: ['10 minutes', '30 minutes', '60 minutes', 'Before discharge'], correct: 0,
      explain: 'Goal: 12-lead ECG within 10 minutes of ED arrival for suspected ACS. For STEMI, the goal is first medical contact–to–device ≤90 minutes (door-to-needle ≤30 minutes if fibrinolysis is used).' },
    { id: 'tria-13', cat: 'triage',
      q: 'A patient at 34 weeks\' gestation has a severe headache, visual changes, and BP 168/112. What is your triage priority and concern?',
      options: ['ESI 4 — migraine', 'ESI 2 — preeclampsia with severe features; risk of eclamptic seizure', 'ESI 5 — refer to OB clinic', 'ESI 3 — routine labor check'], correct: 1,
      explain: 'Severe-range BP (≥160/110) with headache or visual changes suggests preeclampsia with severe features. This is high risk: expedite evaluation, lower BP (labetalol, hydralazine, or oral nifedipine), and anticipate magnesium sulfate for seizure prophylaxis.' },

    // ───────────────────────── MEDS & CALCS ─────────────────────────
    { id: 'meds-01', cat: 'meds',
      q: 'Order: epinephrine 0.01 mg/kg IM for anaphylaxis; the patient weighs 22 kg. Using 1 mg/mL concentration, how many mL do you draw up?',
      options: ['0.11 mL', '0.22 mL', '0.44 mL', '1.1 mL'], correct: 1,
      explain: '0.01 mg/kg × 22 kg = 0.22 mg. At 1 mg/mL, that is 0.22 mL. Always double-check concentration (1 mg/mL vs 0.1 mg/mL) before drawing up epinephrine — a classic high-alert error point.' },
    { id: 'meds-02', cat: 'meds',
      q: 'Suspected septic shock: lactate 4.2, BP 82/50 after 30 mL/kg crystalloid. What\'s next?',
      options: ['Another 30 mL/kg bolus and recheck lactate', 'Start norepinephrine to maintain MAP ≥65', 'Hold fluids and give antibiotics only', 'Transfuse PRBCs regardless of hemoglobin'], correct: 1,
      explain: 'Hypotension persisting after initial fluid resuscitation means vasopressors — norepinephrine first line — to target MAP ≥65, while continuing to reassess volume status. Antibiotics should already have been given within the first hour.' },
    { id: 'meds-03', cat: 'meds',
      q: 'Dopamine is ordered at 5 mcg/kg/min for an 80 kg patient. The bag is 400 mg in 250 mL. What rate do you set?',
      options: ['5 mL/hr', '15 mL/hr', '30 mL/hr', '48 mL/hr'], correct: 1,
      explain: 'Concentration: 400 mg ÷ 250 mL = 1.6 mg/mL = 1,600 mcg/mL. Dose: 5 × 80 = 400 mcg/min × 60 = 24,000 mcg/hr. Rate: 24,000 ÷ 1,600 = 15 mL/hr.' },
    { id: 'meds-04', cat: 'meds',
      q: 'Norepinephrine is ordered at 8 mcg/min. The bag is 4 mg in 250 mL. What is the pump rate?',
      options: ['8 mL/hr', '16 mL/hr', '30 mL/hr', '60 mL/hr'], correct: 2,
      explain: '4 mg ÷ 250 mL = 16 mcg/mL. 8 mcg/min × 60 = 480 mcg/hr. 480 ÷ 16 = 30 mL/hr.' },
    { id: 'meds-05', cat: 'meds',
      q: 'Weight-based heparin for VTE: bolus 80 units/kg. The patient weighs 75 kg. What bolus dose is due?',
      options: ['750 units', '6,000 units', '8,000 units', '1,350 units'], correct: 1,
      explain: '80 units/kg × 75 kg = 6,000 units. Heparin is a high-alert medication: confirm vial strength and perform an independent double-check. The infusion then starts at 18 units/kg/hr (1,350 units/hr for 75 kg).' },
    { id: 'meds-06', cat: 'meds',
      q: 'What is the correct technique for giving adenosine for SVT?',
      options: ['Slow IV push over 2 minutes', 'Rapid IV push through a proximal line, immediately followed by a rapid saline flush', 'IM injection', 'Dilute in 100 mL and infuse over 15 minutes'], correct: 1,
      explain: 'Adenosine\'s half-life is under 10 seconds. Use the most proximal IV (antecubital), push rapidly, and flush immediately (a stopcock or two-syringe technique helps). Expect a brief pause/asystole on the monitor.' },
    { id: 'meds-07', cat: 'meds',
      q: 'What are the amiodarone doses for adult pulseless VF/VT?',
      options: ['150 mg, then 300 mg', '300 mg IV/IO push, then 150 mg', '5 mg/kg, then 10 mg/kg', '1 mg/min infusion only'], correct: 1,
      explain: 'Adult arrest: amiodarone 300 mg IV/IO push first dose, 150 mg for the second. Lidocaine (1–1.5 mg/kg, then 0.5–0.75 mg/kg) is an alternative. For VT with a pulse, amiodarone is 150 mg over 10 minutes.' },
    { id: 'meds-08', cat: 'meds',
      q: 'Adult cardiac arrest: epinephrine 1 mg IV is due. You have a prefilled syringe of 0.1 mg/mL. How much do you give?',
      options: ['1 mL', '10 mL (the entire syringe)', '0.1 mL', '5 mL'], correct: 1,
      explain: '1 mg ÷ 0.1 mg/mL = 10 mL — the entire prefilled syringe. The 1 mg/mL vial (IM anaphylaxis strength) must never be pushed IV undiluted.' },
    { id: 'meds-09', cat: 'meds',
      q: 'Which patient should NOT receive succinylcholine for RSI?',
      options: ['Healthy 30-year-old with an overdose', 'Dialysis patient who missed dialysis with K+ 6.8', 'Asthmatic in respiratory failure', 'Septic patient with a normal potassium'], correct: 1,
      explain: 'Succinylcholine raises K+ by ~0.5 mEq/L (much more in susceptible patients) and is contraindicated with known hyperkalemia, malignant hyperthermia history, and burns/crush/denervation injuries after ~24–72 hours. Use rocuronium instead.' },
    { id: 'meds-10', cat: 'meds',
      q: 'A patient with chronic opioid use is minimally responsive with RR 6. What is the goal of naloxone dosing?',
      options: ['Full wakefulness as fast as possible with 2 mg IV', 'Titrate small doses to adequate spontaneous respirations', 'Give only if pupils are pinpoint', 'Withhold and intubate immediately'], correct: 1,
      explain: 'Titrate (e.g., 0.04–0.4 mg IV increments) to adequate breathing rather than full arousal, to avoid precipitated withdrawal, vomiting, and agitation. Ventilate with a bag-valve mask meanwhile. Observe for re-sedation.' },
    { id: 'meds-11', cat: 'meds',
      q: 'The monitor shows polymorphic VT with a twisting QRS axis (torsades de pointes) in a patient with a long QT. Which medication is indicated?',
      options: ['Procainamide', 'Magnesium sulfate 1–2 g IV', 'Adenosine', 'Sotalol'], correct: 1,
      explain: 'Magnesium sulfate is the drug of choice for torsades. Pulseless torsades is defibrillated. Drugs that prolong QT (procainamide, sotalol, amiodarone) can worsen it; correct K+ and remove offending drugs.' },
    { id: 'meds-12', cat: 'meds',
      q: 'Before starting an insulin infusion for DKA, which lab value must be checked?',
      options: ['Sodium', 'Potassium — do not start insulin if K+ <3.3 mEq/L', 'Magnesium', 'Hemoglobin A1c'], correct: 1,
      explain: 'Insulin drives potassium into cells and can cause life-threatening hypokalemia. If K+ <3.3 mEq/L, replete potassium first and hold insulin. Fluids are started before insulin.' },
    { id: 'meds-13', cat: 'meds',
      q: 'For a bleeding trauma patient, tranexamic acid (TXA) is most beneficial when given within what time frame from injury?',
      options: ['3 hours', '12 hours', '24 hours', 'Any time during the hospital stay'], correct: 0,
      explain: 'CRASH-2: TXA reduces death from bleeding when given within 3 hours of injury (the earlier the better); after 3 hours it may increase bleeding deaths. Adult dose: 1 g IV over 10 min, then 1 g over 8 hours.' }
  ];

  var api = { CATEGORIES: CATEGORIES, QUESTIONS: QUESTIONS };
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.PulseQuestions = api;
})(typeof window !== 'undefined' ? window : this);
